/*drop table customer if exists;
create table customer (id integer integer, name varchar, phone varchar, primary key (id))*/
drop table t_customer if exists;
create table t_customer (id integer generated by default as identity, name varchar(255), phone varchar(255), valid integer not null, primary key (id))